/*----------------------------------------------------------
MASV: 19127102
HO TEN: Vo Hoang Gia Bao
LAB: 03
NGAY: 10/4/2022
----------------------------------------------------------*/
-- CAU LENH TAO DB
CREATE DATABASE QLSV
GO
USE QLSV
GO



/*----------------------------------------------------------
MASV: 19127102
HO TEN: Vo Hoang Gia Bao
LAB: 03
NGAY: 10/4/2022
----------------------------------------------------------*/
-- CAC CAU LENH TAO TABLE
CREATE TABLE SINHVIEN (
MASV NVARCHAR(20) PRIMARY KEY,
HOTEN NVARCHAR(100) NOT NULL,
NGAYSINH DATETIME,
DIACHI NVARCHAR(200),
MALOP VARCHAR(20),
TENDN NVARCHAR(100) NOT NULL,
MATKHAU VARBINARY(MAX) NOT NULL
)
GO

CREATE TABLE NHANVIEN (
MANV VARCHAR(20) PRIMARY KEY,
HOTEN NVARCHAR(100) NOT NULL,
EMAIL VARCHAR(20),
LUONG VARBINARY(MAX),
TENDN NVARCHAR(100) NOT NULL,
MATKHAU VARBINARY(MAX) NOT NULL
)
GO

CREATE TABLE LOP (
MALOP VARCHAR(20) PRIMARY KEY,
TENLOP NVARCHAR(100) NOT NULL,
MANV VARCHAR(20) 
)
GO

/*
ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
GO

ALTER TABLE LOP ADD  CONSTRAINT FK_LOP_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN (MANV)
GO
*/



/*----------------------------------------------------------
MASV: 19127102
HO TEN: Vo Hoang Gia Bao
LAB: 03
NGAY: 10/4/2022
----------------------------------------------------------*/
-- CAU LENH TAO STORED PROCEDURE
CREATE PROC SP_INS_SINHVIEN (
@MASV NVARCHAR(20),
@HOTEN NVARCHAR(100),
@NGAYSINH DATETIME,
@DIACHI NVARCHAR(200),
@MALOP VARCHAR(20),
@TENDN NVARCHAR(100),
@MATKHAU VARCHAR(MAX)
)
AS
INSERT INTO SINHVIEN
VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, HASHBYTES('MD5', @MATKHAU))
GO


IF NOT EXISTS (SELECT * FROM sys.symmetric_keys WHERE symmetric_key_id = 101)
CREATE MASTER KEY ENCRYPTION BY PASSWORD = '19127102'
GO

IF NOT EXISTS (SELECT * FROM sys.certificates WHERE name = 'MyCert')
CREATE CERTIFICATE MyCert WITH SUBJECT = 'MyCert'
GO

IF NOT EXISTS (SELECT * FROM sys.symmetric_keys WHERE name = 'Key1')
CREATE SYMMETRIC KEY Key1 
WITH ALGORITHM = AES_256
ENCRYPTION BY CERTIFICATE MyCert
GO

OPEN SYMMETRIC KEY Key1
DECRYPTION BY CERTIFICATE MyCert
GO

CREATE PROC SP_INS_NHANVIEN (
@MANV VARCHAR(20),
@HOTEN NVARCHAR(100),
@EMAIL VARCHAR(20),
@LUONG INT,
@TENDN NVARCHAR(100),
@MATKHAU VARCHAR(MAX)
)
AS
INSERT INTO NHANVIEN
VALUES (@MANV, @HOTEN, @EMAIL, ENCRYPTBYKEY(KEY_GUID('Key1'), CONVERT(VARCHAR(MAX), @LUONG)), @TENDN, HASHBYTES('SHA1', @MATKHAU))
GO


CREATE PROC SP_SEL_NHANVIEN 
AS 
SELECT MANV, HOTEN, EMAIL, CONVERT(VARCHAR(MAX), DECRYPTBYKEY(LUONG)) AS LUONGCB FROM NHANVIEN
GO



EXEC SP_INS_SINHVIEN 'SV01', 'NGUYEN VAN A', '1/1/1990', '280 AN DUONG VUONG', 'CNTT-K35', 'NVA', '123456'

EXEC SP_INS_NHANVIEN 'NV01', 'NGUYEN VAN A', 'NVA@', 3000000, 'NVA', 'abcd12'

EXEC SP_SEL_NHANVIEN



--SELECT TENDN, MATKHAU FROM SINHVIEN WHERE TENDN = 'NVA' AND convert(varchar(max),MATKHAU,2) = 'E10ADC3949BA59ABBE56E057F20F883E'