/*----------------------------------------------------------
MASV: 19127102
HO TEN: Vo Hoang Gia Bao
MASV: 19127406
HO TEN: Ngo Huy Hoang
MASV: 19127457
HO TEN: Nguyen Tuan Kiet
LAB: 04 - NHOM
NGAY: 1/5/2022
----------------------------------------------------------*/
-- CAU LENH TAO DB
CREATE DATABASE QLSVNhom
GO
USE QLSVNhom
GO



/*----------------------------------------------------------
MASV: 19127102
HO TEN: Vo Hoang Gia Bao
MASV: 19127406
HO TEN: Ngo Huy Hoang
MASV: 19127457
HO TEN: Nguyen Tuan Kiet
LAB: 04 - NHOM
NGAY: 1/5/2022
----------------------------------------------------------*/
-- CAC CAU LENH TAO TABLE
CREATE TABLE SINHVIEN (
MASV NVARCHAR(20) PRIMARY KEY,
HOTEN NVARCHAR(100) NOT NULL,
NGAYSINH DATETIME,
DIACHI NVARCHAR(200),
MALOP VARCHAR(20),
TENDN NVARCHAR(100) NOT NULL,
MATKHAU VARBINARY(MAX) NOT NULL
)
GO

CREATE TABLE NHANVIEN (
MANV VARCHAR(20) PRIMARY KEY,
HOTEN NVARCHAR(100) NOT NULL,
EMAIL VARCHAR(20),
LUONG VARBINARY(MAX),
TENDN NVARCHAR(100) NOT NULL,
MATKHAU VARBINARY(MAX) NOT NULL,
PUBKEY VARCHAR(MAX)
)
GO

CREATE TABLE LOP (
MALOP VARCHAR(20) PRIMARY KEY,
TENLOP NVARCHAR(100) NOT NULL,
MANV VARCHAR(20) 
)
GO

CREATE TABLE HOCPHAN (
MAHP VARCHAR(20) PRIMARY KEY,
TENHP NVARCHAR(100) NOT NULL,
SOTC INT
)
GO

CREATE TABLE BANGDIEM (
MASV NVARCHAR(20),
MAHP VARCHAR(20),
DIEMTHI VARBINARY(MAX),
PRIMARY KEY (MASV, MAHP)
)
GO

ALTER TABLE BANGDIEM ADD CONSTRAINT FK_BANGDIEM_HOCPHAN FOREIGN KEY(MAHP)
REFERENCES HOCPHAN (MAHP)
GO

ALTER TABLE BANGDIEM ADD CONSTRAINT FK_BANGDIEM_SINHVIEN FOREIGN KEY(MASV)
REFERENCES SINHVIEN (MASV)
GO

ALTER TABLE LOP ADD CONSTRAINT FK_LOP_NHANVIEN FOREIGN KEY(MANV)
REFERENCES NHANVIEN (MANV)
GO

ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY(MALOP)
REFERENCES LOP (MALOP)
GO



/*----------------------------------------------------------
MASV: 19127102
HO TEN: Vo Hoang Gia Bao
MASV: 19127406
HO TEN: Ngo Huy Hoang
MASV: 19127457
HO TEN: Nguyen Tuan Kiet
LAB: 04 - NHOM
NGAY: 1/5/2022
----------------------------------------------------------*/
-- CAU LENH TAO STORED PROCEDURE
CREATE PROC SP_INS_PUBLIC_ENCRYPT_NHANVIEN (
@MANV VARCHAR(20),
@HOTEN NVARCHAR(100),
@EMAIL VARCHAR(20),
@LUONG VARCHAR(MAX),
@TENDN NVARCHAR(100),
@MK VARCHAR(MAX),
@PUB VARCHAR(MAX)
)
AS
INSERT INTO NHANVIEN
VALUES (@MANV, @HOTEN, @EMAIL, CONVERT(VARBINARY(MAX), @LUONG), @TENDN, CONVERT(VARBINARY(MAX), @MK), @PUB)
GO


CREATE PROC SP_SEL_PUBLIC_ENCRYPT_NHANVIEN (
@TENDN NVARCHAR(100),
@MK VARCHAR(MAX)
)
AS
SELECT MANV, HOTEN, EMAIL, CONVERT(VARCHAR(MAX), LUONG) AS LUONG FROM NHANVIEN
WHERE TENDN = @TENDN AND CONVERT(VARCHAR(MAX), MATKHAU) = @MK
GO



/*----------------------------------------------------------
MASV: 19127102
HO TEN: Vo Hoang Gia Bao
MASV: 19127406
HO TEN: Ngo Huy Hoang
MASV: 19127457
HO TEN: Nguyen Tuan Kiet
LAB: 04 - NHOM
NGAY: 3/5/2022
----------------------------------------------------------*/
CREATE PROC SP_SEL_PUBLIC_ENCRYPT_ALL_NHANVIEN 
AS 
SELECT MANV, HOTEN, EMAIL, CONVERT(VARCHAR(MAX), LUONG) AS LUONG FROM NHANVIEN
GO


CREATE PROC SP_SEL_PUBLIC_ENCRYPT_LOP_BY_NHANVIEN (
@MANV VARCHAR(20)
)
AS 
SELECT MALOP, TENLOP FROM LOP WHERE MANV = @MANV
GO


CREATE PROC SP_SEL_PUBLIC_ENCRYPT_SINHVIEN_BY_MALOP (
@MALOP VARCHAR(20)
)
AS 
SELECT MASV, HOTEN, NGAYSINH, DIACHI FROM SINHVIEN WHERE MALOP = @MALOP
GO


CREATE PROC SP_SEL_PUBLIC_ENCRYPT_BANGDIEM (
@MASV NVARCHAR(20)
)
AS 
SELECT MAHP, CONVERT(VARCHAR(MAX), DIEMTHI) AS DIEMTHI FROM BANGDIEM WHERE MASV = @MASV
GO


CREATE PROC SP_INS_PUBLIC_ENCRYPT_BANGDIEM (
@MASV NVARCHAR(20),
@MAHP VARCHAR(20),
@DIEMTHI VARCHAR(MAX)
)
AS 
INSERT INTO BANGDIEM
VALUES (@MASV, @MAHP, CONVERT(VARBINARY(MAX), @DIEMTHI))
GO


CREATE PROC SP_INS_PUBLIC_ENCRYPT_SINHVIEN (
@MASV NVARCHAR(20),
@HOTEN NVARCHAR(100),
@NGAYSINH VARCHAR(MAX),
@DIACHI NVARCHAR(200),
@MALOP VARCHAR(20),
@TENDN NVARCHAR(100),
@MATKHAU VARCHAR(MAX)
)
AS
INSERT INTO SINHVIEN
VALUES (@MASV, @HOTEN, CONVERT(DATETIME, @NGAYSINH, 103), @DIACHI, @MALOP, @TENDN, CONVERT(VARBINARY(MAX), @MATKHAU))
GO


CREATE PROC SP_INS_PUBLIC_ENCRYPT_LOP (
@MALOP VARCHAR(20),
@TENLOP NVARCHAR(100),
@MANV VARCHAR(20) 
)
AS
INSERT INTO LOP
VALUES (@MALOP, @TENLOP, @MANV)
GO



INSERT INTO HOCPHAN VALUES('HP1', 'HOC PHAN 1', 4)
INSERT INTO HOCPHAN VALUES('HP2', 'HOC PHAN 2', 4)