/*----------------------------------------------------------
MASV: 19127102
HO TEN: Vo Hoang Gia Bao
LAB: 03
NGAY: 30/4/2022
----------------------------------------------------------*/
-- CAU LENH TAO DB
CREATE DATABASE QLSV
GO
USE QLSV
GO



/*----------------------------------------------------------
MASV: 19127102
HO TEN: Vo Hoang Gia Bao
LAB: 03
NGAY: 30/4/2022
----------------------------------------------------------*/
-- CAC CAU LENH TAO TABLE
CREATE TABLE SINHVIEN (
MASV NVARCHAR(20) PRIMARY KEY,
HOTEN NVARCHAR(100) NOT NULL,
NGAYSINH DATETIME,
DIACHI NVARCHAR(200),
MALOP VARCHAR(20),
TENDN NVARCHAR(100) NOT NULL,
MATKHAU VARBINARY(MAX) NOT NULL
)
GO

CREATE TABLE NHANVIEN (
MANV VARCHAR(20) PRIMARY KEY,
HOTEN NVARCHAR(100) NOT NULL,
EMAIL VARCHAR(20),
LUONG VARBINARY(MAX),
TENDN NVARCHAR(100) NOT NULL,
MATKHAU VARBINARY(MAX) NOT NULL
)
GO

CREATE TABLE LOP (
MALOP VARCHAR(20) PRIMARY KEY,
TENLOP NVARCHAR(100) NOT NULL,
MANV VARCHAR(20) 
)
GO

/*
ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
GO

ALTER TABLE LOP ADD  CONSTRAINT FK_LOP_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN (MANV)
GO
*/



/*----------------------------------------------------------
MASV: 19127102
HO TEN: Vo Hoang Gia Bao
LAB: 03
NGAY: 30/4/2022
----------------------------------------------------------*/
-- CAU LENH TAO STORED PROCEDURE
CREATE PROC SP_INS_ENCRYPT_SINHVIEN (
@MASV NVARCHAR(20),
@HOTEN NVARCHAR(100),
@NGAYSINH DATETIME,
@DIACHI NVARCHAR(200),
@MALOP VARCHAR(20),
@TENDN NVARCHAR(100),
@MATKHAU VARCHAR(MAX)
)
AS
INSERT INTO SINHVIEN
VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, CONVERT(VARBINARY(MAX), @MATKHAU))
GO


CREATE PROC SP_INS_ENCRYPT_NHANVIEN (
@MANV VARCHAR(20),
@HOTEN NVARCHAR(100),
@EMAIL VARCHAR(20),
@LUONG VARCHAR(MAX),
@TENDN NVARCHAR(100),
@MATKHAU VARCHAR(MAX)
)
AS
INSERT INTO NHANVIEN
VALUES (@MANV, @HOTEN, @EMAIL, CONVERT(VARBINARY(MAX), @LUONG), @TENDN, CONVERT(VARBINARY(MAX), @MATKHAU))
GO


CREATE PROC SP_SEL_ENCRYPT_NHANVIEN 
AS 
SELECT MANV, HOTEN, EMAIL, CONVERT(VARCHAR(MAX), LUONG) AS LUONG FROM NHANVIEN
GO



--SELECT TENDN, MATKHAU FROM SINHVIEN WHERE TENDN = 'NVA' AND CONVERT(VARCHAR(MAX), MATKHAU) = '202CB962AC59075B964B07152D234B70'

--SELECT TENDN, MATKHAU FROM NHANVIEN WHERE TENDN = 'NVA' AND CONVERT(VARCHAR(MAX), MATKHAU) = '40BD001563085FC35165329EA1FF5C5ECBDBBEEF'

--EXEC SP_SEL_ENCRYPT_NHANVIEN


